default: &default
  adapter: postgresql

development:
  <<: *default
  database: nanno_development
  username: root


test:
  <<: *default
  database: nano_test

production:
  <<: *default
  database: nano_production
