# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e2cb742d0461914e39d4d8ebd20e947fdbb7f6cec86e264e82853f0222a35cc70f8f6a6172c99451d8e876bef826a771ef4678c5ddfd72579793d5f676188be

test:
  secret_key_base: 7c079e0731c2a787162f9c661bc2accff974fb17951e0b68398975a0494cf4fde0b14d64105c2fdeb2fb0bcb11fbd4fde5eaf0019a689220e61319904ed53b83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
